#! /bin/bash
# Create the Pulseaudio Socket
if [ ! -e /tmp/.netflix-pulse-socket ];
then
    echo -e "${lpurp}Adding Pulseaudio socket at /tmp/.pulse-socket${NC}" 
    pactl load-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/.netflix-pulse-socket
fi

#pulseaudio --kill
#sudo mount -a
#pulseaudio --start
schroot -p -c jessie386 ~/netflix.sh
